apiVersion: apps/v1
kind: Deployment
metadata:
  name: zalo-integration-dev
spec:
  selector:
    matchLabels:
      run: zalo-integration-dev
  replicas: 1
  template:
    metadata:
      labels:
        run: zalo-integration-dev
    spec:
      containers:
        - name: zalo-int-dev
          image: 172.76.10.150:5002/zalo-integration:dev
          imagePullPolicy: Always
          command: ["node"]
          args: ["server.js"]
          ports:
            - containerPort: 80
          env:
          - name: REDIS_HOST
            value: "redis-master"
          - name: REDIS_PORT
            value: "6379"
          - name: MINIO_ACCESS_KEY
            value: "EGN382IMEPNND2JB46PQ"
          - name: MINIO_SECRET_KEY
            value: "5NwA8Cqx2QCJLa8u3SGUwSzRiKs6DhwbBsbpNbkM"
          - name: MINIO_USE_SSL
            value: "false"
          - name: MINIO_PORT
            value: "9000"
          - name: MINIO_END_POINT
            value: "minio-service"
          - name: MINIO_PUBLIC_END_POINT
            value: "http://minio-service"
          - name: MONGODB_URL
            value: "mongodb://foobar:foobarPassword@mongodb-noops-dev.mongodb-noops.svc.cluster.local:27017/simple_db?authSource=simple_db&ssl=false&replicaSet=mongodb-noops-dev&"
          - name: MONGODB_HOST
            value: "mongodb-noops-dev.mongodb-noops.svc.cluster.local"
          - name: MONGODB_ROOT_USER
            value: "foobar"
          - name: MONGODB_ROOT_PASSWORD
            value: "foobarPassword"
          - name: MONGODB_PORT
            value: "27017"
          - name: HOST_APP_PORT
            value: "80"
          - name: APP_PORT
            value: "80"
          - name: APP_HOST
            value: https://zalo-integration-service-dev
          - name: CB_URL
            value: https://clevervn.ap.ngrok.io/api/zalo/reservation/confirmation
          - name: JWT_PRIVATE_KEY
            value: "bd2dcbbe-b333-4c69-bc18-8aaf6ceda89a"
---
apiVersion: v1
kind: Service
metadata:
  name: zalo-integration-service-dev
  labels:
    run: zalo-integration-dev
spec:
  ports:
    - name: https-zalo-integration-dev
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    run: zalo-integration-dev
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: zalo-integration-gateway-dev
spec:
  selectors:
    istio: ingressgateway
  servers:
    - hosts:
        - '*'
      port:
        name: https-zalo-integration-dev
        number: 30502
        protocol: HTTPS
      tls:
        credentialName: clever
        mode: SIMPLE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: zalo-integration-virtualservice-dev
spec:
  hosts:
    - "*"
  gateways:
    - zalo-integration-gateway-dev
  http:
    - match:
        - port: 30502
          hosts:
            - '*'
          uri:
            prefix: /zalo
      rewrite:
        uri: /graphql
      name: https-zalo-integration-dev
      route:
        - destination:
            host: zalo-integration-service-dev
            port:
              number: 80
    - match:
        - port: 30502
          hosts:
            - '*'
          uri:
            prefix: /api
      name: https-zalo-integration-dev-api
      route:
         - destination:
            host: zalo-integration-service-dev
            port:
              number: 80
---
