version: '3'
services:
  minio:
    container_name: minioInfra
    image: minio/minio
    volumes:
      - minio_data:/data
    environment:
      MINIO_ACCESS_KEY: "EGN382IMEPNND2JB46PQ"
      MINIO_SECRET_KEY: "5NwA8Cqx2QCJLa8u3SGUwSzRiKs6DhwbBsbpNbkM"
    ports:
      - "9000:9000"
    command: minio server /data/minio/
    networks:
      - localnetwork
  mongodb:
    container_name: mongodbInfra
    image: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - "mongodb_data:/data/db"
    ports:
      - "27017:27017"
    networks:
      - localnetwork

  redis:
    image: "redis:alpine"
    container_name: redisInfra
    ports:
      - "6379:6379"
    networks:
      - localnetwork

volumes:
  mongodb_data:
    driver: local
  minio_data:
    driver: local

networks:
  localnetwork:
    external: true
