version: '3'
services:
  web:
    build:
      context: .
    command: bash -c "npm run migrate-mongo ; node server.js"
    ports:
      - "4000:4000"
    environment:
      MINIO_ACCESS_KEY: "AKIAIOSFODNN7EXAMPLE"
      MINIO_SECRET_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
      MINIO_USE_SSL: "false"
      MINIO_PORT: 9000
      MINIO_END_POINT: "minio"
      MONGODB_URL: "mongodb://simple:simplePassword@mongodb:27017/simple_db"
      JWT_PRIVATE_KEY: "privateKey"
      JWT_EXPIRES_IN: "1d"
      BCRYPT_SALT_ROUND: 10
      NODE_ENV: "development"
      APP_PORT: 4000
    networks:
      - localnetwork

networks:
  localnetwork:
    external: true
