version: '3'
services:
  web:
    image: 172.76.10.150:5002/sample-project-backend_web:latest
    build:
      context: .
    command: bash -c "npm run migrate-mongo ; npm run minio-init; node server.js"
    ports:
      - "4000:4000"
      - "4001:4001"
      - "80:80"
    environment:
      MINIO_ACCESS_KEY: "EGN382IMEPNND2JB46PQ"
      MINIO_SECRET_KEY: "5NwA8Cqx2QCJLa8u3SGUwSzRiKs6DhwbBsbpNbkM"
      MINIO_USE_SSL: "false"
      MINIO_PORT: 9000
      MINIO_END_POINT: "minio-service"
      MINIO_PUBLIC_END_POINT: "http://minio-service"
      MONGODB_URL: "mongodb://foobar:foobarPassword@mongo-replica-set-svc:27017/simple_db"
      MONGODB_HOST: "mongo-replica-set-svc"
      MONGODB_ROOT_USER: "replicaset-admin"
      MONGODB_ROOT_PASSWORD: "meomeomeo"
      MONGODB_PORT: 27017
      JWT_PRIVATE_KEY: "privateKey"
      JWT_EXPIRES_IN: "1d"
      BCRYPT_SALT_ROUND: 10
      NODE_ENV: "development"
      APP_HOST: http://backend
      APP_PORT: 4000
      HOST_APP_PORT: 4001
      REDIS_HOST: "redis-sentinel"
      REDIS_PORT: 26379
