version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm start
    ports:
      - "4001:4000"
    links:
      - mongodb
      - minio
    depends_on:
      - mongodb
      - minio
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
  minio:
    image: minio/minio
    volumes:
      - data:/data
    environment:
      MINIO_ACCESS_KEY: "AKIAIOSFODNN7EXAMPLE"
      MINIO_SECRET_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    command: minio server /data/minio/
  mongodb:
    image: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "simple"
      MONGO_INITDB_ROOT_PASSWORD: "simplePassword"

    volumes:
      - "mongodb_data:/data/db"
    ports:
      - "27018:27017"
  int-test:
    build:
      context: .
      dockerfile: ./Dockerfile.int-test
    command: npm test
    links:
      - mongodb
      - minio
      - web
    depends_on:
      - mongodb
      - minio
      - web
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
volumes:
  mongodb_data:
    driver: local
  data:
