version: '3'
services:
  webdev:
    build:
      context: .
    command: nodemon --legacy-watch server.js
    ports:
      - "4001:4000"
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    environment:
      MINIO_ACCESS_KEY: "EGN382IMEPNND2JB46PQ"
      MINIO_SECRET_KEY: "5NwA8Cqx2QCJLa8u3SGUwSzRiKs6DhwbBsbpNbkM"
      MINIO_USE_SSL: "false"
      MINIO_PORT: 9000
      MINIO_END_POINT: "minioInfra"
      MONGODB_URL: "mongodb://foobar:foobarPassword@mongodb:27017/simple_db"
      JWT_PRIVATE_KEY: "privateKey"
      JWT_EXPIRES_IN: "1d"
      BCRYPT_SALT_ROUND: 10
      NODE_ENV: "development"
      APP_PORT: 4000
    networks:
      - localnetwork
networks:
  localnetwork:
    external: true
